### ISSUE TITLE
X-Files lists integration

### ISSUE THREAD

**Issue by gioxx** [blocklist-tools/blocklist-tools#13]
Can I propose to integrate X-Files lists?
Repo: https://github.com/gioxx/xfiles

Lists:
https://github.com/gioxx/xfiles/blob/master/filtri.txt
https://github.com/gioxx/xfiles/blob/master/experimental.txt
https://github.com/gioxx/xfiles/blob/master/facebook.txt
https://github.com/gioxx/xfiles/blob/master/siteblock.txt
https://github.com/gioxx/xfiles/blob/master/upd.txt

Thanks :)

**Comment by lightswitch05** [comment]
I'm sorry, but I'm unable to parse Adblock formatted files. Only Hosts or domain lists at this time.

**Comment by gioxx** [comment]
Got it, surely I can work on it because UPD is based on domains.
I'll get back to you as soon as I work on the clean domains list :)

**Comment by gioxx** [comment]
Here we are :-)
https://github.com/gioxx/xfiles/blob/master/domains/upd_domains.txt
